### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by FGRibreau** [tidwall/redcon#1]
Awesome work @tidwall :)

Redcon will be shared next friday morning in our next [RedisWeekly](http://redisweekly.com) :)!

**Comment by tidwall** [comment]
Thanks!

I want to note that the project was originally publish with the title of "Redis Implementation in Go", but this is incorrect and is better stated as "Redis compatible server framework for Go". 

Otherwise the reader may be under the impression that this is something that it isn't.
