### ISSUE TITLE
C#: StackExchange.Redis is Unable to connect to REDCON

### ISSUE THREAD

**Issue by icewukong** [tidwall/redcon#13]
hi @tidwall 

After compiled the example, Go: redigo can connect to the example server, but C#: StackExchange.Redis can't and C#: StackExchange.Redis can connect to tile38 server.

In order to connect to redcon with C#: StackExchange.Redis, what should I do?

**Comment by tidwall** [comment]
hi @icewukong,

It's probably related to this https://github.com/tidwall/tile38/issues/201

Just add an `ECHO` command (https://redis.io/commands/echo)

I also recommend logging the `ERR unknown command` errors on the server side.

**Comment by icewukong** [comment]
After deal with the command: "echo", C#: StackExchange.Redis  can  connect to redcon, and after deal with the commands: "client"、"info"、"subscribe"、"cluster", C#: StackExchange.Redis can imput data from redcon.
Thank you for your helps  :+1:

**Comment by tidwall** [comment]
You’re welcome.
