### ISSUE TITLE
memory leaking when connection is reset with go 1.11.x

### ISSUE THREAD

**Issue by yankeguo** [tidwall/redcon#24]
I built a service using `redcon` and deployed it in production environment.

One day, for some reason (maybe unstable internal networking), massive connection reset occurred, I observed that reset connections are not released and memory keep leaking.

I recompiled my binary with go 1.10.x and 1.9.x, everything is ok, reset connections are released correctly and no memory leaks.

Problem only occur when compiled with go 1.11.x.

I'd investigate this issue and report any progress later.

**Comment by yankeguo** [comment]
And I need some help with simulating tcp connection reset

**Comment by tidwall** [comment]
@yankeguo Are you still seeing this issue?

**Comment by yankeguo** [comment]
@tidwall no, this issue never happened again.
