### ISSUE TITLE
(empty list or set) problem.

### ISSUE THREAD

**Issue by hiqsociety** [tidwall/redcon#30]
I can't seem to generate (empty list or set) with any of the WriteInt WriteString WriteNull or WriteRaw...

how do I return (empty list or set) like normal redis?

127.0.0.1:6380> lrange a 0 1
(empty list or set)

**Comment by tidwall** [comment]
You'll need to use the `WriteArray()` function, followed by each item.

For example, let's say you want to print a list of names.

```go
names := []string{"Ichika", "Marie", "Benjamin", "Aya", "Mamadou"}

conn.WriteArray(len(names))
for _, name := range names {
    conn.WriteBulkString(name)
}
```

The Redcon `Write*` methods follow the [Redis Protocol](https://redis.io/topics/protocol).

**Comment by hiqsociety** [comment]
thx! let me repeat again... you are the best!
