### ISSUE TITLE
how does hmget return values? sorry i'm not sure how to use appendbulk etc without examples.

### ISSUE THREAD

**Issue by gitmko0** [tidwall/redcon#33]
how does hmget return values? sorry i'm not sure how to use appendbulk etc without examples.

**Comment by tidwall** [comment]
According to the Redis website, the [hmget](https://redis.io/commands/hmget) command returns an array of bulk strings.

So you would first use AppendArray followed by a number of AppendBulkString (or AppendBulk for byte slices).

Here's an example of how to create a valid Redis response for the HMGET command from an array of Go strings.

```go
strs := []string{ "hello", "world", "planet" }

var resp []byte
resp = redcon.AppendArray(resp, len(strs))
for _, str := range strs {
    resp = redcon.AppendBulkString(resp, str)
}

```
