### ISSUE TITLE
is it possible to support close idle connection?

### ISSUE THREAD

**Issue by pirDOL** [tidwall/redcon#34]
Long connection is always used for client-side to optimize latency.
Is it possible to support close idle connection on server-side(redcon) to avoid too many idle connections?

**Comment by tidwall** [comment]
There's nothing built in that supports auto closing idle connections.

**Comment by tidwall** [comment]
I just pushed this feature. For example:

```go
s := redcon.NewServer(...)
s.SetIdleClose(time.Minute*5)
s.ListenAndServe()
```
