### ISSUE TITLE
Would pub/sub support be welcome?

### ISSUE THREAD

**Issue by bootjp** [tidwall/redcon#35]
Would I be welcome to implement pub/sub and send a pull request to this repository?

I am in need of a pub/sub right now and if a pull request is welcome, I will implement and send it.

**Comment by tidwall** [comment]
I actually have a pubsub that uses Redcon in a different project.
I think it's a complete implementation. It needs a little cleanup, but I'll push what I have to a branch.

**Comment by tidwall** [comment]
I added a `pubsub` branch -> https://github.com/tidwall/redcon/tree/pubsub

The `example/clone.go` now includes the `subscribe`,  `psubscribe`, and `publish` commands.

**Comment by bootjp** [comment]
Wonderful.
Will this one be merged into the master branch?

**Comment by tidwall** [comment]
Just merged

**Comment by bootjp** [comment]
thankyou!!
