### ISSUE TITLE
Discovered a bug

### ISSUE THREAD

**Issue by gitmko0** [tidwall/redcon#39]
```
<?php

        $qrediswp = new Redis();
        $qrediswp->connect("127.0.0.1", 6379); //dashboard host, port

//hset "e" "432232157184245456" "123456789"

        $lss_disksize = $qrediswp->hget("e","432232157184245456");
        echo '= '.$lss_disksize.' =';

// it shows :123456789 instead of 123456789.
why is there a ":" in front of the value? it doesnt show this using the real redis server.

        exit;
```

Tried with this code...

```
//shows up using this:

                case "hget":

                        if bytes.Compare(cmd.Args[1],[]byte("e"))==0 { //disk space
                                        conn.WriteUint64(uint64(123456789))

                       }

```

**Comment by tidwall** [comment]
> why is there a ":" in front of the value?

The ":" indicates that the value was a [Redis Integer](https://redis.io/topics/protocol#resp-integers). You used `conn.WriteUint64`, which will write a Redis Integer.

> it doesnt show this using the real redis server.

A real Redis server does not use integers for [HSET](https://redis.io/commands/hset) and [HGET](https://redis.io/commands/hget) commands. It uses strings.

I'm wondering if this is a bug with Redcon or is it possible that the PHP Redis client is expecting a string when using the `->hget()` function?

What happens when you use the `redis-cli` command line tool?

**Comment by gitmko0** [comment]
1. I think the PHP Redis client is expecting a string when using the ->hget() function? <--- this seemed more probable.
2. What happens when you use the redis-cli command line tool? 
    it returns "(integer) 123456789"

but... in that case... what do u suggest for cross compatibility? how do i make it so that php redis client will return string if detection from php redis client etc?

i havent try saving a uint64 "integer" in a real redis server using go... i'm curious what's the best way forward to resolve this kind of "surprises"

**Comment by tidwall** [comment]
> what do u suggest for cross compatibility?

For you specific HGET case. I would change  

```go
conn.WriteUint64(uint64(123456789))
```

to

```go
conn.WriteString(fmt.Sprintf("%d", 123456789))
```

> i'm curious what's the best way forward to resolve this kind of "surprises"

For best cross compatibility I recommend that you make sure your Redcon commands response types match a real Redis server response types. For example, the [`INCR`](https://redis.io/commands/incr) returns an integer. So if you want to implement that command in Redcon, and you want the best compatibility across all clients, then I recommend that you return an integer.

**Comment by gitmko0** [comment]
Great work!
i'm looking to replace standard php wordpress redis object cache with this if mget function is written.
u are good at this. my next step is waiting for mget.

what do you suggest for mget?

let's see a pseudocode...
func mget(keys {}interface) {
   var value []byte
    foreach key (keys) {
         append(value,append(append([]byte,key...),[]byte("\n")...)...)
    }
    return value
}

can you do a PR and push this code in for mget example? thx

**Comment by tidwall** [comment]
No. The example has enough commands to show how to use Redcon. You’ll need to implement additional commands on your own.
