### ISSUE TITLE
How to use this service with tile38

### ISSUE THREAD

**Issue by icewukong** [tidwall/redcon#4]
Hi,tidwall
How to use this service with tile38? Can you give me an example?

**Comment by tidwall** [comment]
Hi iceukong,

An older version of the Redcon code is already built directly into Tile38. Redcon is just a Redis compatible server component that facilitates the communication with the client.

I based Redcon off of what I wrote for Tile38 and added some performance enhancements. At some point I'll reinsert the new Redcon back into Tile38.

**Comment by icewukong** [comment]
Oh, I see,thx :)
