### ISSUE TITLE
what's the max concurrent subscriber redcon can take?

### ISSUE THREAD

**Issue by hiqsociety** [tidwall/redcon#40]
Would like to understand how much memory is allocated for each connection.
If you can share some insights to what to look out for for high concurrent connections and how to improve etc, will be great. Have yet to check out the internal mechanics of the code.

**Comment by tidwall** [comment]
There are no maximums or hard limits. It's going to depend on system resources. As far as how much memory pre connection, I recommend that you spin up a test server on the system that you are targeting in production and try a ton of connections. Ideally using a workload that matches what you'd see in production. Then use the `runtime.MemStats` function to analyze the memory usage.

**Comment by hiqsociety** [comment]
Want to stretch the limit. Can you advise what settings to do on linux side?

**Comment by hiqsociety** [comment]
For your "Benchmarks", can you specify whether you have nobinlog enabled on redis side? Just to confirm the 2x performance gain from using redcon that's all. Not sure what setting is used for redis.

**Comment by tidwall** [comment]
I won’t advise on on tweets on you system. You’ll need to discover what works best for you.

**Comment by tidwall** [comment]
The “Benchmarks” describe the settings and system used for redis and redis-benchmark. 
I don’t know what “nobinlog” is, but all disk writes were turned off.
