### ISSUE TITLE
How do you accept port 6380 and socket at the same time?

### ISSUE THREAD

**Issue by hiqsociety** [tidwall/redcon#41]
with reference to this: 
https://github.com/tidwall/redcon/issues/21

How can it be done? I know one or the other but not both.

Thank you for redcon. It's truly amazing.

**Comment by tidwall** [comment]
Your best bet is to listen on both sockets in different goroutines first and share the same handler

```go
package main

import "github.com/tidwall/redcon"

func main() {
	go panic(redcon.ListenAndServeNetwork("tcp", "6380",
		handler, accept, close))
	go panic(redcon.ListenAndServeNetwork("unix", "my-unix-path",
		handler, accept, close))
	select {}
}

func handler(conn redcon.Conn, cmd redcon.Command) {
}
func accept(conn redcon.Conn) bool {

	return true
}
func close(conn redcon.Conn, err error) {

}
```

**Comment by tidwall** [comment]
I'm closing this issue for now. Please feel free to reopen if you have further questions.
