### ISSUE TITLE
zrange possible? :)

### ISSUE THREAD

**Issue by hiqsociety** [tidwall/redcon#42]
it's great software. will be better if you have a roadmap to mention when you think the possibility is to open up all redis compatibility issues.

been using it for awhile now. it's very good.

**Comment by tidwall** [comment]
It's currently feature complete.
It's not meant to replace Redis. It's just a framework for creating Redis compatible services.

**Comment by tidwall** [comment]
All commands must be created by you. Redcon does not provide any built in commands.
