### ISSUE TITLE
error handling differ between redcon & redis 3.0.6/3.2.4

### ISSUE THREAD

**Issue by wleese** [tidwall/redcon#5]
The following simple script shows a difference in behavior between redcon and redis 3.0.6/3.2.4:

`#!/bin/bash

TIMESTAMP=$(TZ=UTC date +"%Y-%m-%dT%H:%M:%S.%3NZ")
HOSTNAME=$(hostname -s)

ROLE=myrole
APPLICATION=myapp
MESSAGE="Ping"
REDISKEY="testkey"
REDIS_SVR="localhost 7379"

PAYLOAD='{ "@fields": { "application": "'${APPLICATION}'", "role": "'${ROLE}'" }, "@message": "'${MESSAGE}'", "@source_host": "'${HOSTNAME}'", "@timestamp": "'${TIMESTAMP}'" }'

(
  echo "RPUSH ${REDISKEY} '"${PAYLOAD}"'"
  sleep 1s
) | telnet $REDIS_SVR`

redcon, in a sense correctly answers:

> -ERR Protocol error: unbalanced quotes in request

redis 3.0.6/3.2.4 however has no gripes with the situation:

> :1

**Comment by tidwall** [comment]
Thanks for reporting this. It does look like the error is correct, but if Redis is accepting this I think Redcon should too. I'll investigate and keep you posted.

**Comment by tidwall** [comment]
Actually the error was wrong. Redcon was not allowing values that are wrapped by apostrophes:

```sh
SET key "hello world"  # works
SET key 'hello world'  # does not work but it should
```

This is fixed now and your script should work as expected.

Thanks a ton!

**Comment by wleese** [comment]
No problem, thanks for the fix!
