### ISSUE TITLE
Unix domain sockets

### ISSUE THREAD

**Issue by bkeroackdsc** [tidwall/redcon#6]
Any chance you could parameterize the [network type](https://github.com/tidwall/redcon/blob/master/redcon.go#L142), so that redcon would support listening on a Unix socket?

**Comment by tidwall** [comment]
Good idea. I added the functions `ListenAndServeNetwork` and `NewServerNetwork`. Let me know if this works for you. Thanks for the suggestion.

**Comment by bkeroackdsc** [comment]
💥 Super quick! Thank you @tidwall

**Comment by tidwall** [comment]
You're welcome. :)
