### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by chrisvdg** [tidwall/redcon#9]
@tidwall , I have added TLS support on a fork because I needed it for a project I'm working on, is there any interest for that feature to be merged into this repo?

**Comment by tidwall** [comment]
Hi @chrisvdg, 
Yes, I can see that being useful to folks.

**Comment by chrisvdg** [comment]
Alright, will make a PR in one of the upcoming days!

**Comment by tidwall** [comment]
I haven't had a chance to review yet, but I hope to in the next few days. Thanks for your patience.

**Comment by chrisvdg** [comment]
Don't worry about it!
I also might need to add graceful shutdown to redcon, but I'll open a separate issue for that when I've implemented it in my fork if I end up needing it.

ps, feedback is quite welcome as I'm just a junior developer.

**Comment by chrisvdg** [comment]
@tidwall, found out my implementation doesn't work, I assumed it was working but using wireshark I found out redigo downgraded my connection to plain tcp. Using tcp.Dial I get the error: `tls: oversized record received with length 21024`.
Looking at wireshark I think your conn overrides the tls handshake and responds to the handshake with ERR command unknown ... (quick assumption from looking at the wireshark results)
![screenshot from 2017-09-18 17-17-42](https://user-images.githubusercontent.com/23582741/30549633-89bf6f86-9c95-11e7-8215-d0fa8ea42f27.png)

Been trying to look into solving this but haven't come up with anything yet.

**Comment by tidwall** [comment]
Thanks for the heads up. I'll wait for your update before reviewing.

**Comment by chrisvdg** [comment]
@tidwall (or someone willing to look into this), I seem to be quite stuck on this one, so would be nice if you could have a look at this if possible.
My current work can be found here: https://github.com/chrisvdg/redcon/tree/adds-tls
And the current state is that redcon doesn't seem to be able to read from the tls connection.
Client side I do seem to be able to write without errors, but it's waiting forever for a reply, my guess is that the server for some reason doesn't receive the message send by the client and therefor doesn't reply.

made a quick test server and client in case someone wants to use it:
https://gist.github.com/chrisvdg/1506c01d5aff077d5d3334bd12bc37cb

**Comment by chrisvdg** [comment]
@tidwall, I think you can review it, works with plain tcp now, but redigo does throw some errors I'll investigate

**Comment by tidwall** [comment]
Thanks for the update, and it looks like Redigo merged your PR too!
